/**
 * Build step: pack samples/demo-project into a base64 module so the Worker can
 * serve the built-in demo without a filesystem.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { crc32 } from 'node:zlib'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const source = join(root, 'samples', 'demo-project')
const output = join(root, 'worker', 'src', 'sample-data.ts')

const SKIP_DIRS = new Set(['.git', 'node_modules', '__pycache__', '.venv', 'venv', 'dist', 'build'])

function walk(directory, files = []) {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) walk(join(directory, entry.name), files)
    } else if (entry.isFile()) {
      const full = join(directory, entry.name)
      if (statSync(full).size <= 2 * 1024 * 1024) files.push(full)
    }
  }
  return files
}

if (!statSync(source, { throwIfNoEntry: false })?.isDirectory()) {
  throw new Error(`Sample project not found at ${source}`)
}

const entries = walk(source).map((full) => ({
  name: relative(source, full).split(sep).join('/'),
  content: readFileSync(full),
}))

// Minimal store-only ZIP writer: no compression keeps this dependency-free and
// the sample is small enough that size is irrelevant.
const chunks = []
const central = []
let offset = 0

for (const entry of entries) {
  const nameBytes = Buffer.from(entry.name, 'utf8')
  const crc = crc32(entry.content)
  const local = Buffer.alloc(30)
  local.writeUInt32LE(0x04034b50, 0)
  local.writeUInt16LE(20, 4)
  local.writeUInt16LE(0, 6)
  local.writeUInt16LE(0, 8) // stored
  local.writeUInt16LE(0, 10)
  local.writeUInt16LE(0, 12)
  local.writeUInt32LE(crc, 14)
  local.writeUInt32LE(entry.content.length, 18)
  local.writeUInt32LE(entry.content.length, 22)
  local.writeUInt16LE(nameBytes.length, 26)
  local.writeUInt16LE(0, 28)
  chunks.push(local, nameBytes, entry.content)

  const header = Buffer.alloc(46)
  header.writeUInt32LE(0x02014b50, 0)
  header.writeUInt16LE(20, 4)
  header.writeUInt16LE(20, 6)
  header.writeUInt32LE(crc, 16)
  header.writeUInt32LE(entry.content.length, 20)
  header.writeUInt32LE(entry.content.length, 24)
  header.writeUInt16LE(nameBytes.length, 28)
  header.writeUInt32LE(offset, 42)
  central.push(header, nameBytes)

  offset += local.length + nameBytes.length + entry.content.length
}

const centralBuffer = Buffer.concat(central)
const end = Buffer.alloc(22)
end.writeUInt32LE(0x06054b50, 0)
end.writeUInt16LE(entries.length, 8)
end.writeUInt16LE(entries.length, 10)
end.writeUInt32LE(centralBuffer.length, 12)
end.writeUInt32LE(offset, 16)

const archive = Buffer.concat([...chunks, centralBuffer, end])

writeFileSync(
  output,
  `/** Generated by scripts/build-sample.mjs. Do not edit. */\n\nexport const SAMPLE_ZIP_BASE64 = '${archive.toString('base64')}'\n`,
  'utf8',
)

console.log(`Bundled ${entries.length} sample files into ${output} (${archive.length} bytes)`)
